# Generated by Django 4.0.4 on 2022-04-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-date', '-time')},
        ),
    ]
