# Generated by Django 4.0.4 on 2022-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
