# Generated by Django 4.0.4 on 2022-04-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='price',
            new_name='fees',
        ),
    ]
