# Generated by Django 4.0.4 on 2022-04-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specializaion',
            new_name='Specialization',
        ),
    ]
