# Generated by Django 4.0.4 on 2022-04-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_arrival_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experince',
            new_name='experience',
        ),
    ]
