# Generated by Django 4.0.4 on 2022-04-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_experince_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
