# Generated by Django 4.0.4 on 2022-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_schedule_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
