# Generated by Django 4.0.4 on 2022-04-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_rename_time_schedule_time_from_schedule_time_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
    ]
